### ISSUE TITLE
How do I use boost libraries after installation

### ISSUE THREAD

**Issue by huanghantao** [MarkusJx/install-boost#1]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/22836925/102303520-49c19600-3f96-11eb-9f78-60c948b68aaf.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/22836925/102303535-53e39480-3f96-11eb-9b63-693538d082c1.png">
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/22836925/102303551-5cd46600-3f96-11eb-9f4a-f5da61c0596e.png">

**Comment by MarkusJx** [comment]
Just take a look at the [test workflow](https://github.com/MarkusJx/install-boost/blob/main/.github/workflows/test-cmake.yml). The Boost root directory path is stored in the output variable ``BOOST_ROOT``. So if you want to use it, first enter an id for the action, lets say ``install-boost``, as in the test workflow.

The boost root directory then can be retrieved using ``${{steps.install-boost.outputs.BOOST_ROOT}}``.  Add that to your include path. Instructions on how to do that [here](https://stackoverflow.com/a/558819), if you need those. Using CMake, you only need to set the BOOST_ROOT as an environment variable like this:
```yml
env:
        BOOST_ROOT: ${{steps.install-boost.outputs.BOOST_ROOT}}
```
Using make, well, I honestly don't know how to do that, just set your include path, the libraries to link against are located in ``${{steps.[INSTALL-BOOST-ID].outputs.BOOST_ROOT}}/lib``.

**Comment by huanghantao** [comment]
Thank you!
