### ISSUE TITLE
env.GITHUB_WORKSPACE evaluated to be null

### ISSUE THREAD

**Issue by DingXuefeng** [MarkusJx/install-boost#12]
Hi, 

The example your provided do not work. `${{env.GITHUB_WORKSPACE}}` evals to null. See [Context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) and [Environment variable](https://docs.github.com/en/actions/learn-github-actions/environment-variables). Should use `${{github.workspace}}` instead.

**Comment by MarkusJx** [comment]
Hi,

thank you for your suggestion. I've changed the readme accordingly :)
