### ISSUE TITLE
Error: Could not find boost version 1.76.0

### ISSUE THREAD

**Issue by RuoyuLiOT-DE** [MarkusJx/install-boost#18]
Hi, thanks for the excellent action first!
I have run into this issue, please see the screenshot for the workflow file and the running log below, not able to find boost, I have tried from 1.71.0 to 1.76.0 and got the same error for all of them, am I doing something wrong in the workflow file?
![image](https://user-images.githubusercontent.com/73345309/183021446-3dbbc01e-dbcc-4e8e-b49c-d6bd79eaa2a7.png)
![image](https://user-images.githubusercontent.com/73345309/183020883-453c15f8-d0ae-427c-a49b-98c455ebd275.png)

**Comment by MarkusJx** [comment]
Hi,
when using any boost version < ``1.78.0`` you *must not* set the ``toolset`` parameter as the [documentation for this parameter states](https://github.com/MarkusJx/install-boost#toolset):
> Selecting this is only supported for boost versions 1.78.0 and higher with the new version of this action or any version with the legacy versions.

This is actually something that comes up quite often so I have to admit that the documentation for that feature is quite poor, I'm sorry for that. I'll probably change the action to emit a warning and ignoring the parameter when set.

I hope this helps :)

**Comment by RuoyuLiOT-DE** [comment]
thanks a lot, problem is solved, it is actually well documented, and it is the user not reading the menu fine enough :p, maybe this just shows how developers on the windows platform suffered from the msvc toolset so they always try to be as explicit as they can.
