### ISSUE TITLE
Error: Error: Could not find boost version 1.74.0

### ISSUE THREAD

**Issue by mjovanc** [MarkusJx/install-boost#23]
When using the following:

```yml
- name: Install Boost
        uses: MarkusJx/install-boost@v2.3.1
        if: matrix.config.os == 'windows-2019'
        id: install-boost
        with:
            boost_version: 1.74.0
            boost_install_dir: C:\Boost\boost_1_74_0
            platform_version: 2019
            toolset: msvc
```

It gives me an error:

```
Run MarkusJx/install-boost@v2.3.1
Starting install-boost@2.1.0
The install directory was manually changed to C:\Boost\boost_1_74_0\boost
Warning: Setting the toolset with boost version < 1.78.0 may cause issues
Downloading versions-manifest.json...
Parsing versions-manifest.json...
Error: Error: Could not find boost version 1.74.0
```

For what I understand in the TypeScript code it should set a default if the version is not set and thus use the V2 and the new JSON file: https://raw.githubusercontent.com/MarkusJx/prebuilt-boost/main/versions-manifest.json

But for some reason it uses this file to parse: https://raw.githubusercontent.com/actions/boost-versions/main/versions-manifest.json

**Comment by MarkusJx** [comment]
Hi,

as the warning states:
> Warning: Setting the toolset with boost version < 1.78.0 may cause issues

You should not define the `toolset` parameter to make this work.
Just don't ask me why I did this, maybe I'll change this behaviour in a future release.

**Comment by MarkusJx** [comment]
Ok, so selecting a toolset for boost versions prior to 1.78 isn't *officially* supported, but I've added a mingw version for boost 1.74 anyways: https://github.com/MarkusJx/prebuilt-boost/issues/3#issuecomment-1339582433

This obviously doesn't work, I'll fix this at some point.
Also, I've moved this issue to #37 as this isn't really part of this issue.
