### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by william-silversmith** [MarkusJx/install-boost#3]
Hi! This action was very helpful for building some python wheels. Do you anticipate adding support for MacOS? I can compile those wheels using my own machine, but my previous laptop is busted and this new one doesn't support py36 and py37. 

Thanks for your consideration!

**Comment by MarkusJx** [comment]
Unfortunately, this doesn't seem to be possible.
This tool uses the prebuilt images from [actions/boost-versions](https://github.com/actions/boost-versions), so the installable versions are limited to those in their [versions manifest](https://github.com/actions/boost-versions/blob/main/versions-manifest.json), which only include boost versions for Windows and linux-based runners.

Honestly, this was primarily designed for windows runners, as you can install boost on linux using ``apt`` and macOs using ``brew``, which is what I'd recommend doing. Another way would be using ``MacPorts``, which also works but isn't as great as ``brew`` but offers a wider range of boost versions (If I recall correctly).

But if you have an Idea on how to add mac support without compiling boost or downloading weird images, let me know (may be impossible, as they added those new chips, whatever), just reopen this issue, if required.

Have a nice day :)
