### ISSUE TITLE
Unexpected failure on MacOS

### ISSUE THREAD

**Issue by Ravenwater** [MarkusJx/install-boost#32]
Getting a weird failure that I am RCAing:

![image](https://user-images.githubusercontent.com/466641/212742587-d71ebb5e-283e-4c4a-bdf6-43e6f3a19689.png)

Hypothesizing that there was some connectivity failure at Github that corrupted the tar file. Rerunning to test that hypothesis. Will add result to this issue when available.

**Comment by Ravenwater** [comment]
Confirmed, just an intermittent failure of the environment:

![image](https://user-images.githubusercontent.com/466641/212743632-3703cf43-6827-488b-8737-254ba7733998.png)

Admin can close this issue when seen.

**Comment by MarkusJx** [comment]
Ok, thanks for letting me know
