### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by channingko-madden** [MarkusJx/install-boost#42]
This action uses Node.js 16, which has reached end-of-life, and [github has initiated the deprecation process for actions using Node.js 16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Workflows using this action display the alert about Node 16 deprecation.

Github advises actions to run on Node 20 instead of Node 16.

**Comment by MarkusJx** [comment]
That's unfortunate, I guess.
Will be fixed by #44.

Thank you for noticing!

**Comment by MarkusJx** [comment]
Fixed in [`v2.4.5`](https://github.com/MarkusJx/install-boost/releases/tag/v2.4.5)
